title: "interTwin Dashboard"
subtitle: "Entry point to interTwin Services"
logo: "assets/intertwin-white.png"
header: true
footer: '<p>Powered by <a href="https://www.intertwin.eu/">interTwin</a> | Dashboard created with <a href="https://github.com/bastienwirtz/homer">Homer</a>.</p>'
columns: 3
connectivityCheck: true

# Colors and branding
colors:
  light:
    highlight-primary: "#000000"
    highlight-secondary: "#ff9900"
    highlight-hover: "#000000"
    background: "#f5f5f5"
    card-background: "#ffffff"
    text: "#333333"
    text-header: "#ffffff"
    text-title: "#000000"
    text-subtitle: "#555555"
    link: "#0073e6"
    link-hover: "#ff9900"

  dark:
    highlight-primary: "#000000"
    highlight-secondary: "#ff9900"
    highlight-hover: "#005bb5"
    background: "#1a1a1a"
    card-background: "#2b2b2b"
    text: "#eaeaea"
    text-header: "#ffffff"
    text-title: "#fafafa"
    text-subtitle: "#cccccc"
    link: "#0073e6"
    link-hover: "#ff9900"
    background-image: "/assets/background-dark.png"  # Custom background image

# Custom fonts
stylesheet:
  - "https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap"

# Default layout
defaults:
  layout: columns
  colorTheme: light

# Services
services:
  - name: "Compute and Cloud Services"
    icon: "fas fa-cloud"
    items:
      - name: "JupyterHub with HPC offloading"
        logo: "assets/jupyter.svg"
        url: "https://jupyter-ukri.intertwin.fedcloud.eu/"
        subtitle: "JupyterHub with interLink support"
        endpoint: "<http://your-host-o-domain>/cors/https://jupyter-ukri.intertwin.fedcloud.eu/"
        timeout: 5000
        target: "_blank"
      - name: "GRNET Openstack"
        logo: "assets/grnet.png"
        url: "https://ui.cloud.grnet.gr/"
        endpoint: "<http://your-host-o-domain>/cors/https://ui.cloud.grnet.gr/"
        subtitle: "Access GRNET Openstack"
        target: "_blank"
        method: "head"
        successCodes: [200, 301, 302, 401, 403]
        timeout: 10000
      - name: "UKRI Openstack"
        logo: "assets/stfc.png"
        url: "https://openstack.stfc.ac.uk/"
        subtitle: "UKRI Openstack Dashboard"
        endpoint: "<http://your-host-o-domain>/cors/https://openstack.stfc.ac.uk/"
        timeout: 5000
        target: "_blank"
    

  - name: "Data Lake Services"
    icon: "fas fa-database"
    items:
      - name: "Rucio"
        logo: "assets/rucio.png"
        url: "https://rucio-intertwin-testbed.desy.de"
        subtitle: "Manage large-scale datasets"
        endpoint: "<http://your-host-o-domain>/cors/https://rucio-intertwin-testbed.desy.de"
        timeout: 5000
        target: "_blank"
      - name: "FTS Monitoring"
        logo: "assets/fts.png"
        url: "https://fts-egi.cern.ch:8449/fts3/ftsmon/"
        endpoint: "<http://your-host-o-domain>/cors/https://fts-egi.cern.ch:8449/fts3/ftsmon/#/"
        timeout: 5000
        subtitle: "Monitor FTS Server"
        target: "_blank"
      - name: "VEGA dCache"
        logo: "assets/dcache.png"
        url: "https://dcache.sling.si:2880/projects/"
        endpoint: "<http://your-host-o-domain>/cors/https://dcache.sling.si:2880/projects/"
        timeout: 5000
        subtitle: "dCache storage system at VEGA"
        target: "_blank"

  - name: "Orchestration and infrastructure management"
    icon: "fas fa-robot"
    items:
      - name: "PaaS Orchestrator"
        logo: "assets/paas.png"
        url: "https://eosc-paas.cloud.ba.infn.it"
        subtitle: "Orchestrate Cloud Deployment"
        endpoint: "<http://your-host-o-domain>/cors/https://eosc-paas.cloud.ba.infn.it/home/login"
        timeout: 5000
        target: "_blank"
      - name: "Infrastructure Manager"
        logo: "assets/im.png"
        url: "https://im.egi.eu"
        subtitle: "Infrastructure Management "
        endpoint: "<http://your-host-o-domain>/cors/https://im.egi.eu"
        timeout: 5000
        target: "_blank"

  - name: "Workflows and AI"
    icon: "fas fa-project-diagram"
    items:
      - name: "openEO"
        logo: "assets/openeo.png"
        url: "https://editor.openeo.org/?server=https%3A%2F%2Fopeneo.intertwin.fedcloud.eu%2F1.1.0%2F"
        subtitle: ""
        endpoint: "<http://your-host-o-domain>/cors/https://editor.openeo.org/?server=https%3A%2F%2Fopeneo.intertwin.fedcloud.eu%2F1.1.0%2F"
        target: "_blank"
      - name: "OSCAR UKRI Cluster"
        logo: "assets/oscar.png"
        url: "https://oscar-ukri.intertwin.fedcloud.eu/"
        subtitle: "OSCAR Cluster Management at UKRI"
        endpoint: "<http://your-host-o-domain>/cors/https://oscar-ukri.intertwin.fedcloud.eu/"
        target: "_blank"
      - name: "OSCAR GRNET Cluster"
        logo: "assets/oscar.png"
        url: "https://oscar-grnet.intertwin.fedcloud.eu/"
        subtitle: "OSCAR Cluster Management at GRNET"
        endpoint: "<http://your-host-o-domain>/cors/https://oscar-grnet.intertwin.fedcloud.eu/"
        target: "_blank"
      - name: "MLFlow"
        logo: "https://mlflow.org/docs/latest/_static/MLflow-logo-final-black.png"
        url: "https://mlflow.intertwin.fedcloud.eu/signup"
        subtitle: "ML Experiment Tracking"
        endpoint: "<http://your-host-o-domain>/cors/https://mlflow.intertwin.fedcloud.eu/signup"
        timeout: 10000
        method: "get"
        successCodes: [200, 301, 302, 401, 403, 418]
        target: "_blank"

  - name: "AAI Services"
    icon: "fas fa-user-shield"
    items:
      - name: "EGI Check-in"
        logo: "assets/egi.png"
        url: "https://aai-demo.egi.eu"
        subtitle: "Access EGI Check-in"
        endpoint: "<http://your-host-o-domain>/cors/https://aai-demo.egi.eu/registry/"
        timeout: 5000
        target: "_blank"
      - name: "ALISE"
        logo: "assets/alise.svg"
        url: "https://alise.data.kit.edu/"
        subtitle: "Map AAI identities to local HPC/HTC accounts"
        endpoint: "<http://your-host-o-domain>/cors/https://alise.data.kit.edu/"
        timeout: 5000
        target: "_blank"

  - name: "SQAaaS"
    icon: "fas fa-tools"
    items:
      - name: "Software Quality as a Service"
        logo: "assets/SQAaaS.png"
        url: "https://sqaaas.eosc-synergy.eu/"
        subtitle: "SQAaaS for interTwin"
        endpoint: "<http://your-host-o-domain>/cors/https://sqaaas.eosc-synergy.eu/"
        timeout: 5000
        target: "_blank"
