version: '3.8'
services:
  homer:
    image: b4bz/homer:latest
    container_name: homer
    ports:
      - "${HOMER_PORT}:8080"
    environment:
      - SIDECAR_STATUS_ENABLED=true
    volumes:
      - ./assets:/www/assets
    restart: unless-stopped
