version: '3.8'
services:
  homer:
    image: b4bz/homer:latest
    container_name: intertwin-dashboard
    ports:
      - "${HOMER_PORT}:8080"
    environment:
      - SIDECAR_STATUS_ENABLED=true
    volumes:
      - ./assets:/www/assets
    restart: unless-stopped
    networks:
      - internal_network

  cors-anywhere:
    image: sourabh385/cors-anywhere:latest
    container_name: cors-anywhere
    environment:
      - NODE_TLS_REJECT_UNAUTHORIZED=0
    ports:
      - "${CORS_PORT}:5000"
    restart: unless-stopped
    networks:
      - internal_network

networks:
  internal_network:
    driver: bridge
    name: internal_network