name: Automerge Pull Requests

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Attempt to automerge
        uses: "pascalgn/automerge-this"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          merge-strategy: "merge"
          merge-method: "squash"
          commit-message: "Merged by CI"
